---
deployment:
  tasks:
    - export DEPLOYPATH=/home/itnr0wu8252x/public_html/
    - /bin/cp * $DEPLOYPATH
    - /bin/cp CSS $DEPLOYPATH
    - /bin/cp JavaScript $DEPLOYPATH
    - /bin/cp Assests $DEPLOYPATH
